### ISSUE TITLE
Metadata Buffer Sample video

### ISSUE THREAD

**Issue by All4Gis** [All4Gis/QGISFMV#51]
It's so strange but metadata buffer not work with this video samples http://samples.ffmpeg.org/MPEG2/mpegts-klv/
Can you please just look at this issue?

**Comment by ltbam** [comment]
I've run one of these videos and came to the following conclusion:

Day Flight.mpg:
The metadata show up the first second and then gets away. That's why the location info show up in the manager.

If you look to the metadata stream, you'll see that there are really few metadata.
ffmpeg.exe -i "C:/temp/Day Flight.mpg" -map data-re -f data "c:\temp\Day Flight.txt"

I think this video does just have metadata for 1 second and the rest or time the metas are empty.

**Comment by All4Gis** [comment]
mmm... I'll try it then. But I think you're right

**Comment by All4Gis** [comment]
you're right,close this issue

**Comment by All4Gis** [comment]
Sorry but is not correct,I'm checking with other tools  and this video have metadata,not only one second!I will try to fix it

**Comment by ltbam** [comment]
To follow up with this issue:

I took the tagged 1.0 Version from QGISFMV (https://github.com/All4Gis/QGISFMV/tree/v1.0) which doesn't have the Metadatabuffer. I checked the video "Day Flight.mpg" and I have the same behaviour than with the Buffer, only the first Metadata appears. Therefore, I don't think the problem lies in the python plugin code, but rather on the external library or in the video itself.

The external ffmpeg call to retrieve the metadata from the video is this one:
C:\LegacySW\ffmpeg-20180619-a990184-win64-static\win\ffmpeg.exe -i "C:/temp/Day Flight.mpg" -ss 00:00:20.8810 -to 00:00:20.9810 -map data-re -f data -

on this video it shows an error:
start time for stream 1 is not set in estimate_timings_from_pts

That mean the video has a timestamp problem and the seeking into the metadata don't work. I've seen a ticket regarding this:

https://trac.ffmpeg.org/ticket/1979

It suggest the addition of -fflags +genpts right after ffmpeg.exe, but it is a workaround, and it does not work in this case.

So for me these videos are not compliant and should be fixed before using with QGISFMV.
